version: '3'
services:
  apache:
    #image: tutum/apache-php
#    image: 'bitnami/apache:latest'
#    build: './apache/'
    container_name: apache
    restart: 'always'
    build: 
      context: './apache'
#      dockerfile: Dockerfile-ubuntu
      dockerfile: Dockerfile-httpd
      args:
        buildno: 1
    ports:
      - '80:80'
      # - '80:80'
#      - '443:443'
    volumes:
      - './public_html:/var/www/html'
      # image: 'bitnami/apache:latest'
   # environment:
   #   - APACHE_HTTP_PORT_NUMBER=8081
    depends_on:
      - php
      - mariadb
  php:
    container_name: php
#    build: './apache/'
    build:
      context: './php'
      dockerfile: Dockerfile
      args:
        buildno: 1
    # image: vuvanphan/phpfpm:7.1.25-fpm-jessie
    volumes:
      - './public_html:/var/www/html'
  mariadb:
    image: 'bitnami/mariadb'
    container_name: mariadb
    restart: 'always'
    environment:
      - MARIADB_ROOT_PASSWORD=mypass123
      - MARIADB_USER=user1
      - MARIADB_PASSWORD=mypassuser123
      - MARIADB_DATABASE=mykinhdoanh
    volumes:
      - 'mariadb_data:/bitnami'
    # ports:
    #   - 3306:80
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: phpmyadmin
    ports:
      - 8080:80
      # - '3306:80'
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    restart: 'always'
    volumes:
      - 'phpmyadmin_data:/bitnami'
volumes:
  mariadb_data:
    driver: local
  phpmyadmin_data:
    driver: local

# link web http://localhost

# link browser phpmyadmin http://localhost:8080
# user : root
# pass : mypass123

## connect mariadb with docker 
# docker exec -it docker-sql_mariadb_1 bash
# mysql -uroot -p
# enter pass : mypass123