FROM httpd:2.4.33-alpine
RUN apk update; \
    apk upgrade;

# # Copy apache vhost file to proxy php requests to php-fpm container
COPY httpd/vitual.apache.conf /usr/local/apache2/conf/vitual.apache.conf

RUN echo "Include /usr/local/apache2/conf/vitual.apache.conf" \
    >> /usr/local/apache2/conf/httpd.conf

## Document Root : /usr/local/apache2/htdocs
## Document Index : /usr/local/apache2/htdocs/index.html